### ISSUE TITLE
GCP Deploy - GitHub Actions Typo

### ISSUE THREAD

**Issue by hiteacheryouare** [denoland/docs#162]
On the docs on deploying a deno app to GCP, they give an example GitHub actions template. This template has a typo (or more of a grammatical error). Here it is:

```yml
    runs-on: ubuntu-latest
    steps:
    - name: CHeckout
      uses: actions/checkout@v3
```

The `H` in `Checkout` should not be capitalized.

It should be a super easy fix. I can create the PR once assigned
